{
 "title": "Security Hub",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Account",
    "query": "{\"find\": \"terms\", \"field\": \"AwsAccountId.keyword\"}"
   },
   {
    "name": "Services",
    "query": "{\"find\": \"terms\", \"field\": \"ControlId_duplicate.keyword\", \"query\": \"AwsAccountId:$Account\"}"
   },
   {
    "name": "Status",
    "query": "{\"find\": \"terms\", \"field\": \"ComplianceStatus.keyword\", \"query\": \"ControlId_duplicate:$Services\"}"
   },
   {
    "name": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"SeverityLabel.keyword\",  \"query\": \"ComplianceStatus:$Status\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "PASSED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "AwsAccountId:$Account AND ControlId_duplicate:$Services AND ComplianceStatus:PASSED AND SeverityLabel:$Severity",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FAILED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "AwsAccountId:$Account AND ControlId_duplicate:$Services AND ComplianceStatus:FAILED AND SeverityLabel:$Severity",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "AwsAccountId:$Account AND ControlId_duplicate:$Services AND ComplianceStatus:$Status AND SeverityLabel:$Severity AND ComplianceStatus:$Status",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Findings",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "AwsAccountId:$Account AND ControlId_duplicate:$Services AND ComplianceStatus:$Status AND SeverityLabel:$Severity AND ComplianceStatus:$Status",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}